openapi: 3.2.0
info:
  title: My Title Heartbeat API
  version: 1.0.0
servers:
- url: https://eggtransport.chaldal.com
tags:
- name: Heartbeat
paths:
  /api/Heartbeat/Smoketest:
    post:
      tags:
      - Heartbeat
      operationId: Heartbeat_Smoketest
      responses:
        '204':
          description: ''
      summary: Heartbeat smoketest
      x-summary-source: derived
  /api/Heartbeat/Ping:
    get:
      tags:
      - Heartbeat
      operationId: Heartbeat_Ping
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
            text/csv:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
      summary: Heartbeat ping
      x-summary-source: derived
x-generator: NSwag v13.10.8.0 (NJsonSchema v10.3.11.0 (Newtonsoft.Json v13.0.0.0))
